"""add invoices
Revision ID: 0f6b994db243
Revises: bac3d45ef78c
Create Date: 2026-07-19 17:25:17.900968
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision: str = '0f6b994db243'
down_revision: Union[str, None] = 'bac3d45ef78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('partner_type', sa.Enum('customer', 'supplier', 'both', name='business_partner_type', native_enum=False, create_constraint=True), server_default='customer', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_key', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=32), nullable=True),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=2), server_default='RO', nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('county', sa.String(length=128), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('iban', sa.String(length=64), nullable=True),
    sa.Column('payment_term_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(country_code) = 2', name='ck_business_partners_country_code_length'),
    sa.CheckConstraint('char_length(name) >= 1', name='ck_business_partners_name_not_empty'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name_key', 'tax_id', name='uq_business_partners_company_name_tax_id')
    )
    op.create_index(op.f('ix_business_partners_company_id'), 'business_partners', ['company_id'], unique=False)
    op.create_index(op.f('ix_business_partners_is_active'), 'business_partners', ['is_active'], unique=False)
    op.create_index(op.f('ix_business_partners_name_key'), 'business_partners', ['name_key'], unique=False)
    op.create_index(op.f('ix_business_partners_partner_type'), 'business_partners', ['partner_type'], unique=False)
    op.create_index(op.f('ix_business_partners_tax_id'), 'business_partners', ['tax_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('business_partner_id', sa.UUID(), nullable=False),
    sa.Column('invoice_type', sa.Enum('sales', 'purchase', name='invoice_type', native_enum=False, create_constraint=True), server_default='sales', nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'partially_paid', 'paid', 'overdue', 'cancelled', name='invoice_status', native_enum=False, create_constraint=True), server_default='draft', nullable=False),
    sa.Column('series', sa.String(length=20), server_default='INV', nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='RON', nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), server_default='1.000000', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('vat_total', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(number) >= 1', name='ck_invoices_number_not_empty'),
    sa.CheckConstraint('char_length(series) >= 1', name='ck_invoices_series_not_empty'),
    sa.CheckConstraint('due_date >= issue_date', name='ck_invoices_due_date_after_issue_date'),
    sa.CheckConstraint('exchange_rate > 0', name='ck_invoices_exchange_rate_positive'),
    sa.CheckConstraint('paid_amount <= total', name='ck_invoices_paid_amount_not_over_total'),
    sa.CheckConstraint('paid_amount >= 0', name='ck_invoices_paid_amount_non_negative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_invoices_subtotal_non_negative'),
    sa.CheckConstraint('total >= 0', name='ck_invoices_total_non_negative'),
    sa.CheckConstraint('vat_total >= 0', name='ck_invoices_vat_total_non_negative'),
    sa.ForeignKeyConstraint(['business_partner_id'], ['business_partners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'invoice_type', 'series', 'number', name='uq_invoices_company_type_series_number')
    )
    op.create_index(op.f('ix_invoices_business_partner_id'), 'invoices', ['business_partner_id'], unique=False)
    op.create_index(op.f('ix_invoices_company_id'), 'invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_type'), 'invoices', ['invoice_type'], unique=False)
    op.create_index(op.f('ix_invoices_issue_date'), 'invoices', ['issue_date'], unique=False)
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('product_code', sa.String(length=64), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=16), server_default='buc', nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), server_default='1.0000', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), server_default='0.0000', nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), server_default='19.00', nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name='ck_invoice_lines_discount_percent_range'),
    sa.CheckConstraint('gross_amount >= 0', name='ck_invoice_lines_gross_amount_non_negative'),
    sa.CheckConstraint('net_amount >= 0', name='ck_invoice_lines_net_amount_non_negative'),
    sa.CheckConstraint('position >= 1', name='ck_invoice_lines_position_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_lines_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_invoice_lines_unit_price_non_negative'),
    sa.CheckConstraint('vat_amount >= 0', name='ck_invoice_lines_vat_amount_non_negative'),
    sa.CheckConstraint('vat_rate >= 0 AND vat_rate <= 100', name='ck_invoice_lines_vat_rate_range'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'position', name='uq_invoice_lines_invoice_position')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_product_code'), 'invoice_lines', ['product_code'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_lines_product_code'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_issue_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_type'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_company_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_business_partner_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_business_partners_tax_id'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_partner_type'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_name_key'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_is_active'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_company_id'), table_name='business_partners')
    op.drop_table('business_partners')
    # ### end Alembic commands ###
