"""add accounting core
Revision ID: 7ba66c4dfec0
Revises: 185456d1d73f
Create Date: 2026-07-18 08:16:25.864704
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '7ba66c4dfec0'
down_revision: Union[str, None] = '185456d1d73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'locked', name='accounting_period_status', native_enum=False, create_constraint=True), server_default='open', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_accounting_periods_month_range'),
    sa.CheckConstraint('start_date <= end_date', name='ck_accounting_periods_date_range'),
    sa.CheckConstraint('year >= 2000 AND year <= 2200', name='ck_accounting_periods_year_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'year', 'month', name='uq_accounting_periods_company_year_month')
    )
    op.create_index(op.f('ix_accounting_periods_company_id'), 'accounting_periods', ['company_id'], unique=False)
    op.create_index(op.f('ix_accounting_periods_month'), 'accounting_periods', ['month'], unique=False)
    op.create_index(op.f('ix_accounting_periods_status'), 'accounting_periods', ['status'], unique=False)
    op.create_index(op.f('ix_accounting_periods_year'), 'accounting_periods', ['year'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_class', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Enum('asset', 'liability', 'equity', 'income', 'expense', 'off_balance', name='account_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('nature', sa.Enum('debit', 'credit', 'bifunctional', name='account_nature', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source', sa.Enum('template', 'manual', 'imported', name='account_source', native_enum=False, create_constraint=True), server_default='manual', nullable=False),
    sa.Column('allows_posting', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_analytic', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('account_class >= 1 AND account_class <= 9', name='ck_accounts_class_range'),
    sa.CheckConstraint('char_length(code) >= 1', name='ck_accounts_code_not_empty'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_accounts_company_code')
    )
    op.create_index(op.f('ix_accounts_account_class'), 'accounts', ['account_class'], unique=False)
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_company_id'), 'accounts', ['company_id'], unique=False)
    op.create_index(op.f('ix_accounts_is_active'), 'accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_accounts_parent_id'), 'accounts', ['parent_id'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_parent_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_active'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_company_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_class'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_accounting_periods_year'), table_name='accounting_periods')
    op.drop_index(op.f('ix_accounting_periods_status'), table_name='accounting_periods')
    op.drop_index(op.f('ix_accounting_periods_month'), table_name='accounting_periods')
    op.drop_index(op.f('ix_accounting_periods_company_id'), table_name='accounting_periods')
    op.drop_table('accounting_periods')
    # ### end Alembic commands ###
