"""add journal entries
Revision ID: bac3d45ef78c
Revises: 7ba66c4dfec0
Create Date: 2026-07-18 12:58:44.952619
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'bac3d45ef78c'
down_revision: Union[str, None] = '7ba66c4dfec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('accounting_period_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('display_number', sa.String(length=64), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('document_number', sa.String(length=128), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('currency_code', sa.String(length=3), server_default='RON', nullable=False),
    sa.Column('status', sa.Enum('draft', 'posted', 'reversed', name='journal_entry_status', native_enum=False, create_constraint=True), server_default='draft', nullable=False),
    sa.Column('source', sa.Enum('manual', 'document', 'import', 'ai', 'reversal', name='journal_entry_source', native_enum=False, create_constraint=True), server_default='manual', nullable=False),
    sa.Column('origin_type', sa.Enum('manual', 'document', 'bank_statement', 'payroll', 'inventory', 'fixed_asset', 'vat_adjustment', 'opening_balance', 'closing_entry', 'ai', 'other', name='journal_origin_type', native_enum=False, create_constraint=True), server_default='manual', nullable=False),
    sa.Column('origin_id', sa.UUID(), nullable=True),
    sa.Column('is_system_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('posted_by_id', sa.UUID(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_entry_id', sa.UUID(), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(currency_code) = 3', name='ck_journal_entries_currency_code_length'),
    sa.CheckConstraint('char_length(display_number) >= 1', name='ck_journal_entries_display_number_not_empty'),
    sa.CheckConstraint('fiscal_year >= 2000 AND fiscal_year <= 2200', name='ck_journal_entries_fiscal_year_range'),
    sa.CheckConstraint('sequence >= 1', name='ck_journal_entries_sequence_positive'),
    sa.ForeignKeyConstraint(['accounting_period_id'], ['accounting_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_entry_id'], ['journal_entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'display_number', name='uq_journal_entries_company_display_number'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'sequence', name='uq_journal_entries_company_year_sequence'),
    sa.UniqueConstraint('reversed_entry_id')
    )
    op.create_index(op.f('ix_journal_entries_accounting_period_id'), 'journal_entries', ['accounting_period_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_company_id'), 'journal_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_created_by_id'), 'journal_entries', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_deleted_at'), 'journal_entries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_journal_entries_document_number'), 'journal_entries', ['document_number'], unique=False)
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_fiscal_year'), 'journal_entries', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_journal_entries_origin_id'), 'journal_entries', ['origin_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_origin_type'), 'journal_entries', ['origin_type'], unique=False)
    op.create_index(op.f('ix_journal_entries_source'), 'journal_entries', ['source'], unique=False)
    op.create_index(op.f('ix_journal_entries_status'), 'journal_entries', ['status'], unique=False)
    op.create_table('journal_entry_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('currency_code', sa.String(length=3), server_default='RON', nullable=False),
    sa.Column('foreign_amount', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), server_default='1', nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (debit > 0 AND credit > 0)', name='ck_journal_entry_lines_not_both_debit_credit'),
    sa.CheckConstraint('char_length(currency_code) = 3', name='ck_journal_entry_lines_currency_code_length'),
    sa.CheckConstraint('credit >= 0', name='ck_journal_entry_lines_credit_non_negative'),
    sa.CheckConstraint('debit >= 0', name='ck_journal_entry_lines_debit_non_negative'),
    sa.CheckConstraint('exchange_rate > 0', name='ck_journal_entry_lines_exchange_rate_positive'),
    sa.CheckConstraint('foreign_amount >= 0', name='ck_journal_entry_lines_foreign_amount_non_negative'),
    sa.CheckConstraint('line_number >= 1', name='ck_journal_entry_lines_line_number_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_entry_id', 'line_number', name='uq_journal_entry_lines_entry_line_number')
    )
    op.create_index(op.f('ix_journal_entry_lines_account_id'), 'journal_entry_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_lines_journal_entry_id'), 'journal_entry_lines', ['journal_entry_id'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entry_lines_journal_entry_id'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_journal_entry_lines_account_id'), table_name='journal_entry_lines')
    op.drop_table('journal_entry_lines')
    op.drop_index(op.f('ix_journal_entries_status'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_source'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_origin_type'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_origin_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_fiscal_year'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_document_number'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_deleted_at'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_created_by_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_company_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_accounting_period_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
